name: ESPHome Builder
description: Builds ESPHome binaries

inputs:
  yaml_file:
    description: YAML file to use
    required: true
    type: string
  version:
    description: Version of ESPHome to build
    required: false
    type: string
    default: latest

outputs:
  name:
    description: Name of device extracted from configuration
  version:
    description: ESPHome version

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.yaml_file }}

branding:
  icon: 'archive'
  color: 'white'
